--[[
    Generated by tools/keycodes.sh from waywall's own source.
    Do not edit by hand; tests/run.lua checks this against
    schema/keycodes.txt and will fail if the two drift apart.
]]

local M = {}

M.keys = {
    "ESC",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "MINUS",
    "EQUAL",
    "BACKSPACE",
    "TAB",
    "Q",
    "W",
    "E",
    "R",
    "T",
    "Y",
    "U",
    "I",
    "O",
    "P",
    "LEFTBRACE",
    "RIGHTBRACE",
    "ENTER",
    "LEFTCTRL",
    "A",
    "S",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    "SEMICOLON",
    "APOSTROPHE",
    "GRAVE",
    "LEFTSHIFT",
    "BACKSLASH",
    "Z",
    "X",
    "C",
    "V",
    "B",
    "N",
    "M",
    "COMMA",
    "DOT",
    "SLASH",
    "RIGHTSHIFT",
    "KPASTERISK",
    "LEFTALT",
    "SPACE",
    "CAPSLOCK",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "NUMLOCK",
    "SCROLLLOCK",
    "KP7",
    "KP8",
    "KP9",
    "KPMINUS",
    "KP4",
    "KP5",
    "KP6",
    "KPPLUS",
    "KP1",
    "KP2",
    "KP3",
    "KP0",
    "KPDOT",
    "ZENKAKUHANKAKU",
    "102ND",
    "F11",
    "F12",
    "RO",
    "KATAKANA",
    "HIRAGANA",
    "HENKAN",
    "KATAKANAHIRAGANA",
    "MUHENKAN",
    "KPJPCOMMA",
    "KPENTER",
    "RIGHTCTRL",
    "KPSLASH",
    "SYSRQ",
    "RIGHTALT",
    "LINEFEED",
    "HOME",
    "UP",
    "PAGEUP",
    "LEFT",
    "RIGHT",
    "END",
    "DOWN",
    "PAGEDOWN",
    "INSERT",
    "DELETE",
    "MACRO",
    "MUTE",
    "VOLUMEDOWN",
    "VOLUMEUP",
    "POWER",
    "KPEQUAL",
    "KPPLUSMINUS",
    "PAUSE",
    "SCALE",
    "KPCOMMA",
    "HANGEUL",
    "HANGUEL",
    "HANJA",
    "YEN",
    "LEFTMETA",
    "RIGHTMETA",
    "COMPOSE",
    "STOP",
    "AGAIN",
    "PROPS",
    "UNDO",
    "FRONT",
    "COPY",
    "OPEN",
    "PASTE",
    "FIND",
    "CUT",
    "HELP",
    "MENU",
    "CALC",
    "SETUP",
    "SLEEP",
    "WAKEUP",
    "FILE",
    "SENDFILE",
    "DELETEFILE",
    "XFER",
    "PROG1",
    "PROG2",
    "WWW",
    "MSDOS",
    "COFFEE",
    "SCREENLOCK",
    "ROTATE_DISPLAY",
    "DIRECTION",
    "CYCLEWINDOWS",
    "MAIL",
    "BOOKMARKS",
    "COMPUTER",
    "BACK",
    "FORWARD",
    "CLOSECD",
    "EJECTCD",
    "EJECTCLOSECD",
    "NEXTSONG",
    "PLAYPAUSE",
    "PREVIOUSSONG",
    "STOPCD",
    "RECORD",
    "REWIND",
    "PHONE",
    "ISO",
    "CONFIG",
    "HOMEPAGE",
    "REFRESH",
    "EXIT",
    "MOVE",
    "EDIT",
    "SCROLLUP",
    "SCROLLDOWN",
    "KPLEFTPAREN",
    "KPRIGHTPAREN",
    "NEW",
    "REDO",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "PLAYCD",
    "PAUSECD",
    "PROG3",
    "PROG4",
    "ALL_APPLICATIONS",
    "DASHBOARD",
    "SUSPEND",
    "CLOSE",
    "PLAY",
    "FASTFORWARD",
    "BASSBOOST",
    "PRINT",
    "HP",
    "CAMERA",
    "SOUND",
    "QUESTION",
    "EMAIL",
    "CHAT",
    "SEARCH",
    "CONNECT",
    "FINANCE",
    "SPORT",
    "SHOP",
    "ALTERASE",
    "CANCEL",
    "BRIGHTNESSDOWN",
    "BRIGHTNESSUP",
    "MEDIA",
    "SWITCHVIDEOMODE",
    "KBDILLUMTOGGLE",
    "KBDILLUMDOWN",
    "KBDILLUMUP",
    "SEND",
    "REPLY",
    "FORWARDMAIL",
    "SAVE",
    "DOCUMENTS",
    "BATTERY",
    "BLUETOOTH",
    "WLAN",
    "UWB",
    "VIDEO_NEXT",
    "VIDEO_PREV",
    "BRIGHTNESS_CYCLE",
    "BRIGHTNESS_AUTO",
    "BRIGHTNESS_ZERO",
    "DISPLAY_OFF",
    "WWAN",
    "WIMAX",
    "RFKILL",
    "MICMUTE",
}

M.buttons = {
    "lmb",
    "m1",
    "mouse1",
    "leftmouse",
    "rmb",
    "m2",
    "mouse2",
    "rightmouse",
    "mmb",
    "m3",
    "mouse3",
    "middlemouse",
    "m4",
    "mb4",
    "mouse4",
    "m5",
    "mb5",
    "mouse5",
}

--[[
    Lower-cased lookup, because waywall matches these with strcasecmp.
]]
local lookup = {}
for _, list in ipairs({ M.keys, M.buttons }) do
    for _, name in ipairs(list) do
        lookup[name:lower()] = name
    end
end

--[[
    Does waywall recognise this as a remap source or target?
]]
function M.valid(name)
    if type(name) ~= "string" then
        return false
    end
    return lookup[name:lower():match("^%s*(.-)%s*$")] ~= nil
end

--[[
    Drop remaps waywall cannot parse, loudly.

    config_parse_remap returning non-zero aborts the *entire* config load, so
    one unknown name costs every mode, mirror and keybind in the document. The
    symptom is "toolwall stopped working", which sends you looking anywhere
    but at the rebind you just added.

    Remaps are matched against the keycode table above - the names from
    linux/input-event-codes.h - and not against the keysyms that keybinds use.
    The two agree on letters, digits and function keys and disagree on
    everything else, so "Escape" and "bracketleft" are the shape this goes
    wrong in.

    The GUI validates before writing, so a table only arrives here bad if it
    was hand-edited or came from someone else's config.
]]
function M.sane(remaps, label)
    if type(remaps) ~= "table" then
        return {}
    end

    local util = require("toolwall.util")
    local out = {}

    for from, to in pairs(remaps) do
        if not M.valid(from) then
            util.warn(("%s: waywall has no input named %q, dropping that rebind")
                :format(label or "remaps", tostring(from)))
        elseif not M.valid(to) then
            util.warn(("%s: %q is remapped to %q, which waywall has no name for")
                :format(label or "remaps", tostring(from), tostring(to)))
        else
            out[from] = to
        end
    end

    return out
end

return M
