#!/usr/bin/env sh
# Regenerate the remap name tables from a waywall checkout.
#
# waywall is the authority on which names input.remaps accepts, and the list
# grows when upstream adds keys. Re-run this against a newer checkout rather
# than editing the tables by hand.
#
# Writes two files from the one source:
#   schema/keycodes.txt          read by toolwall-core at compile time
#   runtime/toolwall/keycodes.lua  read by the runtime and the importer
#
# tests/run.lua checks the two agree, so a hand-edit of either is caught.
#
# Usage: tools/keycodes.sh [path-to-waywall-checkout]   (default ~/waywall)
set -eu

WW="${1:-$HOME/waywall}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/schema/keycodes.txt"
LUA_OUT="$ROOT/runtime/toolwall/keycodes.lua"

KEYCODES="$WW/include/util/keycodes.h"
CONFIG="$WW/waywall/config/config.c"

for f in "$KEYCODES" "$CONFIG"; do
    if [ ! -f "$f" ]; then
        echo "not a waywall checkout: $f missing" >&2
        exit 1
    fi
done

{
    echo "# waywall's remap name table, the source of truth for input.remaps."
    echo "#"
    echo "# Remaps are parsed by config_parse_remap, which matches each half"
    echo "# case-insensitively against util_keycodes (linux/input-event-codes.h"
    echo "# names, NOT X11 keysyms) and then against button_mappings. Keybinds"
    echo "# use keysyms and are a different vocabulary entirely - do not mix them."
    echo "#"
    echo "# Extracted from waywall include/util/keycodes.h and"
    echo "# waywall/config/config.c. Regenerate with tools/keycodes.sh."
    echo
    echo "[keys]"
    grep -o 'K([A-Z0-9_]*)' "$KEYCODES" | sed 's/K(//;s/)//'
    echo
    echo "[buttons]"
    sed -n '/} button_mappings\[\] = {/,/^};/p' "$CONFIG" | grep -o '"[a-z0-9]*"' | tr -d '"'
} > "$OUT"

{
    echo "--[["
    echo "    Generated by tools/keycodes.sh from waywall's own source."
    echo "    Do not edit by hand; tests/run.lua checks this against"
    echo "    schema/keycodes.txt and will fail if the two drift apart."
    echo "]]"
    echo
    echo "local M = {}"
    echo
    echo "M.keys = {"
    grep -o 'K([A-Z0-9_]*)' "$KEYCODES" | sed 's/K(/    "/;s/)/",/'
    echo "}"
    echo
    echo "M.buttons = {"
    sed -n '/} button_mappings\[\] = {/,/^};/p' "$CONFIG" |
        grep -o '"[a-z0-9]*"' | sed 's/^/    /;s/$/,/'
    echo "}"
    echo
    cat <<'LUA'
--[[
    Lower-cased lookup, because waywall matches these with strcasecmp.
]]
local lookup = {}
for _, list in ipairs({ M.keys, M.buttons }) do
    for _, name in ipairs(list) do
        lookup[name:lower()] = name
    end
end

--[[
    Does waywall recognise this as a remap source or target?
]]
function M.valid(name)
    if type(name) ~= "string" then
        return false
    end
    return lookup[name:lower():match("^%s*(.-)%s*$")] ~= nil
end

--[[
    Drop remaps waywall cannot parse, loudly.

    config_parse_remap returning non-zero aborts the *entire* config load, so
    one unknown name costs every mode, mirror and keybind in the document. The
    symptom is "toolwall stopped working", which sends you looking anywhere
    but at the rebind you just added.

    Remaps are matched against the keycode table above - the names from
    linux/input-event-codes.h - and not against the keysyms that keybinds use.
    The two agree on letters, digits and function keys and disagree on
    everything else, so "Escape" and "bracketleft" are the shape this goes
    wrong in.

    The GUI validates before writing, so a table only arrives here bad if it
    was hand-edited or came from someone else's config.
]]
function M.sane(remaps, label)
    if type(remaps) ~= "table" then
        return {}
    end

    local util = require("toolwall.util")
    local out = {}

    for from, to in pairs(remaps) do
        if not M.valid(from) then
            util.warn(("%s: waywall has no input named %q, dropping that rebind")
                :format(label or "remaps", tostring(from)))
        elseif not M.valid(to) then
            util.warn(("%s: %q is remapped to %q, which waywall has no name for")
                :format(label or "remaps", tostring(from), tostring(to)))
        else
            out[from] = to
        end
    end

    return out
end

return M
LUA
} > "$LUA_OUT"

echo "wrote $OUT"
echo "wrote $LUA_OUT"
