//! The boat eye sensitivity maths, ported from gore's calculator.
//!
//! <https://arjuncgore.github.io/waywall-boat-eye-calc/>
//!
//! Two calculations live there and both are here, because the second is
//! useless on its own to anyone arriving from Windows.
//!
//!   1. **Reverse boat eye.** Your Minecraft sensitivity means something
//!      different once the pointer acceleration your old system applied is
//!      gone. This converts the number you had into the one that turns your
//!      hand the same distance without it.
//!   2. **Boat eye.** Given a Minecraft sensitivity, produce the fixed
//!      sensitivity everyone measures at, plus the waywall multipliers that
//!      make normal and tall resolutions turn the same amount per count.
//!
//! Ported expression for expression rather than rearranged, because the
//! answer has to agree with the calculator people are already using. The
//! tests check it against values generated by running that JavaScript.
//!
//! Credits, from the calculator's own readme: qmax and r0hkx for the reverse
//! calculation, Esensats for mcsr-calcsens.

use std::f64::consts::PI;

/// The sensitivity boat eye is measured at. Not a default, a constant: the
/// whole point is that everyone is on the same number.
pub const BOAT_EYE_MC_SENS: f64 = 0.02291165;

/// Vertical FOV the tall coefficient is derived at, in degrees.
pub const DEFAULT_VFOV: f64 = 30.0;

/// The heights the calculator assumes when you do not say otherwise.
pub const DEFAULT_NORMAL_HEIGHT: u32 = 1080;
pub const DEFAULT_TALL_HEIGHT: u32 = 16384;

/// Windows' pointer speed slider, which is 1 to 20 and not linear.
///
/// Index 0 is unused so the slider position indexes directly, the way it does
/// in the calculator.
const WINDOWS_STEPS: [f64; 21] = [
    0.0, 0.03125, 0.0625, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0, 1.25, 1.5, 1.75, 2.0,
    2.25, 2.5, 2.75, 3.0, 3.25, 3.5,
];

/// What was scaling your mouse before, if anything.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Pointer {
    /// Already 1:1. Nothing to undo.
    Flat,
    /// The Windows pointer speed slider, 1 to 20, 10 being the middle notch.
    Windows(u8),
    /// libinput's acceleration speed, -1 to 1, 0 being unscaled.
    Linux(f64),
}

/// What to put in Minecraft and in the config.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Sens {
    /// Goes in Minecraft's own sensitivity slider.
    pub mc: f64,
    /// waywall sensitivity at normal resolutions.
    pub normal: f64,
    /// waywall sensitivity while a tall resolution is active.
    pub tall: f64,
}

/// Minecraft turns this much per count. Cubic, which is why halving the
/// slider does not halve the turn.
fn effective(mc: f64) -> f64 {
    (mc * 0.6 + 0.2).powf(3.0) * 8.0
}

/// The same curve at the scale the reverse calculation was written in.
fn dpc(mc: f64) -> f64 {
    (mc * 0.6 + 0.2).powf(3.0) * 1.2
}

/// Undo the cube: the slider position that turns this much per count.
fn mc_from_dpc(value: f64) -> f64 {
    let raw = ((value / 1.2).cbrt() - 0.2) / 0.6;
    raw.clamp(0.0, 1.0)
}

/// How much of the vertical FOV you can actually see when the framebuffer is
/// taller than the window showing it.
fn visible_vfov(v_deg: f64, display_h: f64, fb_h: f64) -> f64 {
    let k = display_h / fb_h;
    (2.0 * ((v_deg * PI / 180.0 / 2.0).tan() * k).atan()) * (180.0 / PI)
}

/// The multiplier a Windows pointer speed step applies, if it is a real step.
pub fn windows_multiplier(step: u8) -> Option<f64> {
    if step < 1 || step > 20 {
        return None;
    }
    Some(WINDOWS_STEPS[step as usize])
}

/// Part one: the sensitivity you would have needed with no pointer scaling.
///
/// Errors describe what is wrong with the input, so they can go straight on
/// screen.
pub fn without_pointer_scaling(mc: f64, pointer: Pointer) -> Result<f64, String> {
    if !(0.0..=1.0).contains(&mc) || mc.is_nan() {
        return Err("Minecraft sensitivity has to be between 0 and 1".into());
    }

    let multiplier = match pointer {
        Pointer::Flat => return Ok(mc),
        Pointer::Windows(step) => windows_multiplier(step)
            .ok_or_else(|| "Windows pointer speed has to be a whole number from 1 to 20".to_string())?,
        Pointer::Linux(speed) => {
            if !(-1.0..=1.0).contains(&speed) || speed.is_nan() {
                return Err("Linux pointer speed has to be between -1 and 1".into());
            }
            1.0 + speed
        }
    };

    if multiplier == 0.0 {
        return Err("that pointer speed scales everything to zero".into());
    }

    Ok(mc_from_dpc(dpc(mc) / multiplier))
}

/// Part two: the boat eye sensitivity and the waywall multipliers for it.
///
/// `normal_height` and `tall_height` are framebuffer heights, which is what
/// decides how much of the vertical FOV a tall resolution actually shows.
pub fn boat_eye(mc: f64, normal_height: u32, tall_height: u32, vfov: f64) -> Sens {
    let scale = effective(mc) / effective(BOAT_EYE_MC_SENS);
    let normal = scale;

    let tall = if tall_height == 0 || normal_height == 0 {
        normal
    } else {
        let vfov_normal = visible_vfov(vfov, normal_height as f64, normal_height as f64);
        let vfov_tall = visible_vfov(vfov, normal_height as f64, tall_height as f64);
        normal / (vfov_normal / vfov_tall)
    };

    Sens { mc: BOAT_EYE_MC_SENS, normal, tall }
}

/// Both halves, which is how the calculator is actually used.
pub fn calculate(
    mc: f64,
    pointer: Pointer,
    normal_height: u32,
    tall_height: u32,
    vfov: f64,
) -> Result<Sens, String> {
    let flat = without_pointer_scaling(mc, pointer)?;
    Ok(boat_eye(flat, normal_height, tall_height, vfov))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Tight enough that a real difference in the maths shows up, loose
    /// enough to survive the last bit of a cube root.
    fn close(got: f64, want: f64, what: &str) {
        let tolerance = want.abs().max(1.0) * 1e-12;
        assert!(
            (got - want).abs() <= tolerance,
            "{what}: got {got}, the calculator says {want}"
        );
    }

    // Every expected value below came out of the calculator's own JavaScript,
    // run against the same inputs. See the module docs for the source.

    #[test]
    fn boat_eye_matches_the_calculator() {
        let cases = [
            (0.0, 0.8192000383401025, 0.05526274455665273),
            (0.02291165, 1.0, 0.0674594018191557),
            (0.1, 1.7997824842332046, 0.12141224979096603),
            (0.3, 5.618893062974761, 0.379047164914081),
            (0.5, 12.800000599064097, 0.8634803836976988),
            (0.7, 24.404788342189985, 1.6463324230872411),
            (1.0, 52.42880245376656, 3.536815651625775),
        ];

        for (mc, normal, tall) in cases {
            let got = boat_eye(mc, DEFAULT_NORMAL_HEIGHT, DEFAULT_TALL_HEIGHT, DEFAULT_VFOV);
            assert_eq!(got.mc, BOAT_EYE_MC_SENS, "the target never moves");
            close(got.normal, normal, "normal");
            close(got.tall, tall, "tall");
        }
    }

    #[test]
    fn the_tall_coefficient_follows_the_framebuffer_height() {
        // A tall resolution no taller than the window needs no correction at
        // all, which is the one case you can check by eye.
        let same = boat_eye(0.5, 1080, 1080, DEFAULT_VFOV);
        close(same.tall, same.normal, "tall equals normal at the same height");

        let half = boat_eye(0.5, 1080, 8192, DEFAULT_VFOV);
        close(half.tall, 1.7264224556016685, "tall at 8192");
    }

    #[test]
    fn windows_pointer_speed_is_undone() {
        let cases = [
            (1u8, 1.0, 52.42880245376656),
            (6, 0.7166008749123943, 25.600001198128194),
            (10, 0.5, 12.800000599064097),
            (14, 0.3280837716534165, 6.400000299532053),
            (20, 0.21552813000695792, 3.6571430283040276),
        ];

        for (step, converted, normal) in cases {
            let flat = without_pointer_scaling(0.5, Pointer::Windows(step)).unwrap();
            close(flat, converted, "converted sensitivity");

            let got = calculate(0.5, Pointer::Windows(step), 1080, 16384, DEFAULT_VFOV).unwrap();
            close(got.normal, normal, "normal");
        }
    }

    #[test]
    fn libinput_acceleration_is_undone() {
        let cases = [
            (-0.5, 0.7166008749123943, 25.600001198128194),
            (0.0, 0.5, 12.800000599064097),
            (0.5, 0.394650387280249, 8.533333732709396),
            (1.0, 0.3280837716534165, 6.400000299532053),
        ];

        for (speed, converted, normal) in cases {
            let flat = without_pointer_scaling(0.5, Pointer::Linux(speed)).unwrap();
            close(flat, converted, "converted sensitivity");

            let got = calculate(0.5, Pointer::Linux(speed), 1080, 16384, DEFAULT_VFOV).unwrap();
            close(got.normal, normal, "normal");
        }
    }

    #[test]
    fn a_conversion_that_would_go_past_the_slider_stops_at_it() {
        // Windows 1 is a sixteenth of normal speed, so undoing it asks for a
        // sensitivity past the end of the slider. The calculator clamps, and
        // so do we, rather than handing back a number Minecraft cannot take.
        let flat = without_pointer_scaling(0.9, Pointer::Windows(1)).unwrap();
        assert_eq!(flat, 1.0);

        let low = without_pointer_scaling(0.0, Pointer::Linux(1.0)).unwrap();
        assert!((0.0..=1.0).contains(&low), "clamped at the bottom too: {low}");
    }

    #[test]
    fn flat_changes_nothing() {
        // Someone who never had pointer acceleration should get the plain
        // calculation, not a rounded version of it.
        let flat = without_pointer_scaling(0.37, Pointer::Flat).unwrap();
        assert_eq!(flat, 0.37);
    }

    #[test]
    fn bad_input_says_what_is_wrong() {
        assert!(without_pointer_scaling(1.5, Pointer::Flat).is_err());
        assert!(without_pointer_scaling(-0.1, Pointer::Flat).is_err());
        assert!(without_pointer_scaling(0.5, Pointer::Windows(0)).is_err());
        assert!(without_pointer_scaling(0.5, Pointer::Windows(21)).is_err());
        assert!(without_pointer_scaling(0.5, Pointer::Linux(2.0)).is_err());

        // -1 is a real slider position, and it scales to nothing.
        assert!(without_pointer_scaling(0.5, Pointer::Linux(-1.0)).is_err());
    }
}
